# distributed training
nodes: 1
gpus: 4
nr: 0
workers: 0
visible_gpus: "0,1,2,3"

# Paths
data_root: "/home/r20user17/Documents/ABIDE_pcp/cpac/filt_noglobal"
train_csv: "./datasets/splits/ABIDE_Training.csv"
test_csv: "./datasets/splits/ABIDE_Testing.csv"
val_csv: "./datasets/splits/ABIDE_Validation.csv"
checkpoints: "./checkpoints"

# Model Options
model: "GraphTransformer"

# Dataset Options
dataset: "ABIDE_BNT"
task: "DX"
atlas: "cc400"
cnp: "AGE_AT_SCAN, BMI"
cp: "SEX, HANDEDNESS_CATEGORY, CURRENT_MED_STATUS"

# Training Options
seed: 42
batch_size: 30
epochs: 100

# Optimization options
optimizer: "Adam"
pcgrad: False
lr: 1.0e-4
dropout: 0.4
weight_decay: 0.01
warmup_epochs: 10
scheduler: False
