# distributed training
nodes: 1
gpus: 4
nr: 0
workers: 8
visible_gpus: "4,5,6,7"

# Paths
data_root: "/home/r20user17/Documents/ABIDE_pcp/cpac/filt_noglobal"
train_csv: "./datasets/splits/ABIDE_Training.csv"
test_csv: "./datasets/splits/ABIDE_Testing.csv"
val_csv: "./datasets/splits/ABIDE_Validation.csv"
checkpoints: "./checkpoints"
reload: "./checkpoints/ComTF_dpl_ABIDE_BNT_cc400_DX_AUC_0.7794_.pth"
results: "./results"

# Model Options
model: "ComTF"
n_heads: 9

# Dataset Options
dataset: "ABIDE_BNT"
task: "DX"
atlas: "cc400"
cnp: "AGE_AT_SCAN"
cp: "SEX"
fusion: "dpl" # early, late, intermediate, dpl, or none

# Training Options
seed: 42
batch_size: 30
epochs: 30

# Optimization options
optimizer: "Adam"
pcgrad: False
lr: 1.0e-4
dropout: 0.4
weight_decay: 0.01
warmup_epochs: 10
scheduler: False
