# distributed training
nodes: 1
gpus: 4
nr: 0
workers: 8
visible_gpus: "0,1,2,3"

# Paths
data_root: "/home/r20user17/Documents/ADHD200"
csv_path: "./datasets/splits"
checkpoints: "./checkpoints"

# Model Options
model: "BolT"
n_heads: 9

# Dataset Options
dataset: "ADHD200"
task: "DX"
atlas: "ho"
cnp: "Age, Performance IQ"
cp: "Gender, Med Status"

# Training Options
seed: 42
batch_size: 30 # BrainGB requires a smaller batch size 20
epochs: 20

# Optimization options
optimizer: "Adam"
pcgrad: False
lr: 1.0e-4
dropout: 0.5
weight_decay: 0.01
warmup_epochs: 10
scheduler: False
