# distributed training
nodes: 1
gpus: 4
nr: 0
workers: 0
visible_gpus: "0,1,2,3"

# Paths
data_root: "/home/r20user17/Documents/ADHD200"
train_csv: "./datasets/splits/ADHD200_Training.csv"
test_csv: "./datasets/splits/ADHD200_Testing.csv"
checkpoints: "./checkpoints"

# Model Options
model: "GraphTransformer"

# Dataset Options
dataset: "ADHD200"
task: "DX"
atlas: "cc400"
cnp: "Age, Performance IQ"
cp: "Gender, Med Status"

# Training Options
seed: 42
batch_size: 30
epochs: 100

# Optimization options
optimizer: "Adam"
pcgrad: False
lr: 1.0e-4
dropout: 0.5
weight_decay: 0.01
warmup_epochs: 10
scheduler: False
