# distributed training
nodes: 1
gpus: 2
nr: 0
workers: 4
visible_gpus: "0,1"

# Paths
data_root: "/home/featurize/work/PanLI_2024_7_30/ADHD200"
csv_path: "./datasets/splits"
checkpoints: "./checkpoints"

# Model Options
model: "DICE"
n_heads: 9

# Dataset Options
dataset: "ADHD200"
task: "DX"
atlas: "cc200"
cnp: "Age, Performance IQ"
cp: "Gender"
fusion: "early" # early, late, intermediate, or none

# Training Options
seed: 42
batch_size: 30 # BrainGB requires a smaller batch size 20
epochs: 100

# Optimization options
optimizer: "Adam"
pcgrad: False
lr: 1.0e-4
dropout: 0.5
weight_decay: 0.1
warmup_epochs: 10
scheduler: False
